---
name: Build
'on':
  push:
    branches:
    - main
    tags:
    - "**"
  pull_request_target:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      TERRAFORM_VERSION: 1.2.7
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Download Terraform
      run: "./scripts/download_terraform.sh $TERRAFORM_VERSION"
    - name: Check format
      run: "~/tfbin/terraform fmt -write=false -diff=true -check"
    - name: Post to hook-exporter
      run: "./.github/exporter.sh"
      env:
        EXPORTER_TOKEN: "${{ secrets.EXPORTER_TOKEN }}"
        JOB_STATUS: "${{ job.status }}"
      if: "${{ always() }}"
